"""Create officers table

Revision ID: 209cd94b2786
Revises: 32da10246552
Create Date: 2026-01-23 12:27:56.552694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209cd94b2786'
down_revision = '32da10246552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officers')
    # ### end Alembic commands ###
