"""remove recommendation and priority columns

Revision ID: 609e618a52a9
Revises: 88242ec43f63
Create Date: 2026-03-08 23:53:53.821376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '609e618a52a9'
down_revision = '88242ec43f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_health', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('crop_health_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('recommendation')
        batch_op.drop_column('priority')
        batch_op.drop_column('remark_date')
        batch_op.drop_column('officer_id')

    with op.batch_alter_table('soil_health', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('soil_health_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('recommendation')
        batch_op.drop_column('priority')
        batch_op.drop_column('remark_date')
        batch_op.drop_column('officer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remark_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('priority', mysql.ENUM('Low', 'Medium', 'High'), nullable=False))
        batch_op.add_column(sa.Column('recommendation', mysql.TEXT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('soil_health_ibfk_2'), 'officers', ['officer_id'], ['id'])

    with op.batch_alter_table('crop_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remark_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('priority', mysql.ENUM('Low', 'Medium', 'High'), nullable=False))
        batch_op.add_column(sa.Column('recommendation', mysql.TEXT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('crop_health_ibfk_3'), 'officers', ['officer_id'], ['id'])

    # ### end Alembic commands ###
