"""added advisory model

Revision ID: 693acfa3c43b
Revises: 609e618a52a9
Create Date: 2026-03-09 01:12:40.056893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693acfa3c43b'
down_revision = '609e618a52a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('High', 'Medium', 'Low'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advisory')
    # ### end Alembic commands ###
