"""add officer advisory fields

Revision ID: 88242ec43f63
Revises: 98762fe12bce
Create Date: 2026-03-07 01:33:31.451614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88242ec43f63'
down_revision = '98762fe12bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Enum('Low', 'Medium', 'High'), nullable=False))
        batch_op.add_column(sa.Column('officer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remark_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'officers', ['officer_id'], ['id'])

    with op.batch_alter_table('soil_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Enum('Low', 'Medium', 'High'), nullable=False))
        batch_op.add_column(sa.Column('officer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remark_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'officers', ['officer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_health', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('remark_date')
        batch_op.drop_column('officer_id')
        batch_op.drop_column('priority')
        batch_op.drop_column('recommendation')

    with op.batch_alter_table('crop_health', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('remark_date')
        batch_op.drop_column('officer_id')
        batch_op.drop_column('priority')
        batch_op.drop_column('recommendation')

    # ### end Alembic commands ###
