"""Added cascade delete to farmer relations

Revision ID: 98762fe12bce
Revises: 1d3a3821863c
Create Date: 2026-02-18 22:50:22.846032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98762fe12bce'
down_revision = '1d3a3821863c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_health', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('crop_health_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'farmers', ['farmer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('farm_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('farm_records_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'farmers', ['farmer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('soil_health', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('soil_health_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'farmers', ['farmer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_health', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('soil_health_ibfk_1'), 'farmers', ['farmer_id'], ['id'])

    with op.batch_alter_table('farm_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('farm_records_ibfk_2'), 'farmers', ['farmer_id'], ['id'])

    with op.batch_alter_table('crop_health', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('crop_health_ibfk_2'), 'farmers', ['farmer_id'], ['id'])

    # ### end Alembic commands ###
